version: '3.6'

services:
    splunk:
        image: "splunk/splunk:${SPLUNK_VERSION}"
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changed!
            - SPLUNK_APPS_URL=https://github.com/splunk/sdk-app-collection/releases/download/v1.0.0/sdk-app-collection.tgz
        volumes:
            - ./examples/github_forks:/opt/splunk/etc/apps/github_forks
            - ./examples/random_numbers:/opt/splunk/etc/apps/random_numbers
            - ./examples/searchcommands_app/package:/opt/splunk/etc/apps/searchcommands_app
            - ./splunklib:/opt/splunk/etc/apps/searchcommands_app/lib/splunklib
            - ./examples/twitted/twitted:/opt/splunk/etc/apps/twitted
        ports:
            - 8000:8000
            - 8088:8088
            - 8089:8089
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
