name: Python CI

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python: [ 2.7, 3.7 ]
        splunk-version:
          - "8.0"
          - "latest"
      fail-fast: false

    services:
      splunk:
        image: splunk/splunk:${{matrix.splunk-version}}
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_HEC_TOKEN: 11111111-1111-1111-1111-1111111111113
          SPLUNK_PASSWORD: changed!
          SPLUNK_APPS_URL: https://github.com/splunk/sdk-app-collection/releases/download/v1.1.0/sdkappcollection.tgz
        ports:
          - 8000:8000
          - 8088:8088
          - 8089:8089
        volumes:
            - "${{env.GITHUB_WORKSPACE}}/tests/searchcommands/test_apps/eventing_app:/opt/splunk/etc/apps/eventing_app"
            - "${{env.GITHUB_WORKSPACE}}/tests/searchcommands/test_apps/generating_app:/opt/splunk/etc/apps/generating_app"
            - "${{env.GITHUB_WORKSPACE}}/tests/searchcommands/test_apps/reporting_app:/opt/splunk/etc/apps/reporting_app"
            - "${{env.GITHUB_WORKSPACE}}/tests/searchcommands/test_apps/streaming_app:/opt/splunk/etc/apps/streaming_app"
            - "${{env.GITHUB_WORKSPACE}}/splunklib:/opt/splunk/etc/apps/eventing_app/lib/splunklib"
            - "${{env.GITHUB_WORKSPACE}}/splunklib:/opt/splunk/etc/apps/generating_app/lib/splunklib"
            - "${{env.GITHUB_WORKSPACE}}/splunklib:/opt/splunk/etc/apps/reporting_app/lib/splunklib"
            - "${{env.GITHUB_WORKSPACE}}/splunklib:/opt/splunk/etc/apps/streaming_app/lib/splunklib"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Test Execution
        run: tox -e py
